language: node_js
node_js:
  - '6'
before_script:
  - npm install
script:
  - npm run test:ci
env:
  - BROWSER=Chrome
  - BROWSER='Mac Safari 9.0'
  - BROWSER='Mac Firefox 46.0'
  - BROWSER='IE 9'
  - BROWSER='IE 10'
  - BROWSER='IE 11'
  - BROWSER='Android 4.2'
  - BROWSER='Android 4.3'
  - BROWSER='Android 4.4'
  - BROWSER='Android 5.0'
  - BROWSER='Android 5.1'
  - BROWSER='iOS 8.0'
  - BROWSER='iOS 8.1'
  - BROWSER='iOS 9.2'
